name: hstl_gpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0
  - scipy
  - pyyaml
  - opencv
  - tqdm
  - cudatoolkit=11.7
  - pip
  - pip:
    - torch==1.13.1+cu117
    - torchvision==0.14.1+cu117
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - tensorboard
    - einops
    - pytorch-metric-learning